common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.signup, name='signup'),
    path('profile/', views.profile, name="profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('', base_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    
    # question_views.py
    path('question/', question_views.question_list, name='question_list'),
    path('question/<int:question_id>/', question_views.question_detail, name='question_detail'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name="answer_create"),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name="answer_vote"),
    path('answer/', answer_views.answer_list, name='answer_list'),

]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question

def index(request):
    return render(request, 'home.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" type"text/css"="type" text/css""="text/css" "" href="{% static 'bootstrap.min.css' %} ">
    <!--pybo CSS-->
    <link rel="stylesheet" type"text/css"="type" text/css""="text/css" "" href="{% static 'style.css' %} ">
    <!--Bootstrap JS-->
    <script src="{% static 'bootstrap.min.js' %}" defer="defer"></script>
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>

  <body>
    <!--네비게이션바-->
    {% include "navbar.html" %}

    <!--기본 템플릿 안에 삽입될 내용 Start-->
    {% block content %}{% endblock %}
    <!--기본 템플릿 안에 삽입될 내용 End-->

    <!--javascript start-->
    {% block script %}{% endblock %}
    <!--javascript end-->
  </body>

</html>

templates/form_errors.html
<!--필드오류와 넌필드 오류를 출력한다-->
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      <!--필드오류-->
      {% if field.errors %}
        <div>
          <strong>{{ field.label }}</strong>
          {{ field.errors }}
        </div>
      {% endif %}
    {% endfor %}

    <!--넌필드오류-->
    {% for error in form.non_field_errors %}
      <div>
        <strong>{{ error }}</strong>
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/home.html
{% extends 'base.html' %}
{% block title %}
  안녕하세요~
{% endblock %}
{% block content %}
  <ul class="list-group">
    <li class="list-group-item list-group-item-action">
      <a href="{% url 'pybo:question_list' %}">질문답변게시판</a>
    </li>
    <li class="list-group-item list-group-item-action">
      <a href="{% url 'pybo:answer_list' %}">최근답변</a>
    </li>
    <li class="list-group-item list-group-item-action">
      <a href="#">홍보게시판</a>
    </li>
    <li class="list-group-item list-group-item-action">
      <a href="http://127.0.0.1:8000/admin">관리자페이지</a>
    </li>
  </ul>
{% endblock %}

templates/navbar.html
<!--네비게이션바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a href="{% url 'pybo:index' %}" class="navbar-brand">Pybo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a href="{% url 'common:logout' %}" class="nav-link">{{ user.username }}
              (로그아웃)</a>
          {% else %}
            <a href="{% url 'common:login' %}" class="nav-link">로그인</a>
          {% endif %}
        </li>
        <li>
          {% if not user.is_authenticated %}
            <a href="{% url 'common:signup' %}" class="nav-link">회원가입</a>
          {% endif %}
        </li>
        <li>
          {% if user.is_authenticated %}
            <a href="{% url 'common:profile' %}" class="nav-link small">프로필 보기</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>